# Generated by Django 5.2.15 on 2026-07-12 20:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('required_hours', models.PositiveIntegerField(verbose_name='必要工数（時間）')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_number', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='社員番号は5桁の半角数字で入力してください。', regex='^\\d{5}$')], verbose_name='社員番号')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='姓')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, verbose_name='名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('available_hours', models.PositiveIntegerField(verbose_name='稼働可能時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'target_month')},
            },
        ),
        migrations.CreateModel(
            name='TaskEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='対象月')),
                ('allocated_hours', models.PositiveIntegerField(verbose_name='今月の予定工数(時間)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_efforts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project', 'target_month')},
            },
        ),
    ]
